### PR TITLE
Fix capitalization of path for newer OS versions

### LINKED ISSUE #3: sqlite3.OperationalError: unable to open database file
This is on macOS 10.10; I don't have much experience with sqlite3, but I can help troubleshoot.

```
seedbox:notifwd gia$ ./notifwd.py

  _   _       _   _ _____             _
 | \ | | ___ | |_(_)  ___|_      ____| |
 |  \| |/ _ \| __| | |_  \ \ /\ / / _` |
 | |\  | (_) | |_| |  _|  \ V  V / (_| |
 |_| \_|\___/ \__|_|_|     \_/\_/ \__,_|

notifwd by Jordan Mann. Starting up... Traceback (most recent call last):
  File "/Users/gia/notifwd/./notifwd.py", line 200, in <module>
    Notification.main(argv)
  File "/Users/gia/notifwd/./notifwd.py", line 78, in main
    Notification.setup(argv)
  File "/Users/gia/notifwd/./notifwd.py", line 65, in setup
    Notification.connection = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file
```

### PR DESCRIPTION
**Pull request by PTrottier**
Fixes #3 in the code. Works on Monterey 12.0.1.

### CODE REVIEW

**Comment by jrmann100** [comment]
This is awesome @PTrottier! Could we have it fall back to the old capitalization if the new path fails, to make this compatible with users who haven't upgraded?

**Comment by PTrottier** [comment]
Apologies for the delay @jrmann100, the code is ready for review/testing and the commits can be squashed and merged.

**Review by jrmann100 — APPROVED** [review]
Looks good!

**Comment by jrmann100** [comment]
Thanks so much @PTrottier!

**Pull request merged**
